In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
from sklearn.metrics import confusion_matrix

In [3]:
crx = pd.read_csv("./crx.csv")
data = pd.read_csv("./data.csv")

In [4]:
crx

att1   att2    att3 att4 att5 att6 att7  att8 att9 att10  att11 att12  \
0      b  30.83   0.000    u    g    w    v  1.25    t     t      1     f   
1      a  58.67   4.460    u    g    q    h  3.04    t     t      6     f   
2      a   24.5   0.500    u    g    q    h  1.50    t     f      0     f   
3      b  27.83   1.540    u    g    w    v  3.75    t     t      5     t   
4      b  20.17   5.625    u    g    w    v  1.71    t     f      0     f   
..   ...    ...     ...  ...  ...  ...  ...   ...  ...   ...    ...   ...   
685    b  21.08  10.085    y    p    e    h  1.25    f     f      0     f   
686    a  22.67   0.750    u    g    c    v  2.00    f     t      2     t   
687    a  25.25  13.500    y    p   ff   ff  2.00    f     t      1     t   
688    b  17.92   0.205    u    g   aa    v  0.04    f     f      0     f   
689    b     35   3.375    u    g    c    h  8.29    f     f      0     t   

    att13 att14  att15 label  
0       g   202      0     +  
1       g    43    560     +  
2       g   280    824     +  
3       g   100      3     +  
4       s   120      0     +  
..    ...   ...    ...   ...  
685     g   260      0     -  
686     g   200    394     -  
687     g   200      1     -  
688     g   280    750     -  
689     g     0      0     -  

[690 rows x 16 columns]

In [5]:
data

ID Diagnosis      3      4       5       6        7        8  \
0      842302         M  17.99  10.38  122.80  1001.0  0.11840  0.27760   
1      842517         M  20.57  17.77  132.90  1326.0  0.08474  0.07864   
2    84300903         M  19.69  21.25  130.00  1203.0  0.10960  0.15990   
3    84348301         M  11.42  20.38   77.58   386.1  0.14250  0.28390   
4    84358402         M  20.29  14.34  135.10  1297.0  0.10030  0.13280   
..        ...       ...    ...    ...     ...     ...      ...      ...   
564    926424         M  21.56  22.39  142.00  1479.0  0.11100  0.11590   
565    926682         M  20.13  28.25  131.20  1261.0  0.09780  0.10340   
566    926954         M  16.60  28.08  108.30   858.1  0.08455  0.10230   
567    927241         M  20.60  29.33  140.10  1265.0  0.11780  0.27700   
568     92751         B   7.76  24.54   47.92   181.0  0.05263  0.04362   

           9       10  ...      23     24      25      26       27       28  \
0    0.30010  0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560   
1    0.08690  0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660   
2    0.19740  0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450   
3    0.24140  0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630   
4    0.19800  0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500   
..       ...      ...  ...     ...    ...     ...     ...      ...      ...   
564  0.24390  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130   
565  0.14400  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220   
566  0.09251  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940   
567  0.35140  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810   
568  0.00000  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444   

         29      30      31  Unnamed: 31  
0    0.7119  0.2654  0.4601      0.11890  
1    0.2416  0.1860  0.2750      0.08902  
2    0.4504  0.2430  0.3613      0.08758  
3    0.6869  0.2575  0.6638      0.17300  
4    0.4000  0.1625  0.2364      0.07678  
..      ...     ...     ...          ...  
564  0.4107  0.2216  0.2060      0.07115  
565  0.3215  0.1628  0.2572      0.06637  
566  0.3403  0.1418  0.2218      0.07820  
567  0.9387  0.2650  0.4087      0.12400  
568  0.0000  0.0000  0.2871      0.07039  

[569 rows x 32 columns]

In [6]:
crx1 = crx.replace("?", np.nan)
crx1 = crx1.dropna()
index = []
for i in range(crx1.shape[0]):
    index.append(i)
crx1.index = index

In [7]:
crx1

att1   att2    att3 att4 att5 att6 att7  att8 att9 att10  att11 att12  \
0      b  30.83   0.000    u    g    w    v  1.25    t     t      1     f   
1      a  58.67   4.460    u    g    q    h  3.04    t     t      6     f   
2      a   24.5   0.500    u    g    q    h  1.50    t     f      0     f   
3      b  27.83   1.540    u    g    w    v  3.75    t     t      5     t   
4      b  20.17   5.625    u    g    w    v  1.71    t     f      0     f   
..   ...    ...     ...  ...  ...  ...  ...   ...  ...   ...    ...   ...   
648    b  21.08  10.085    y    p    e    h  1.25    f     f      0     f   
649    a  22.67   0.750    u    g    c    v  2.00    f     t      2     t   
650    a  25.25  13.500    y    p   ff   ff  2.00    f     t      1     t   
651    b  17.92   0.205    u    g   aa    v  0.04    f     f      0     f   
652    b     35   3.375    u    g    c    h  8.29    f     f      0     t   

    att13 att14  att15 label  
0       g   202      0     +  
1       g    43    560     +  
2       g   280    824     +  
3       g   100      3     +  
4       s   120      0     +  
..    ...   ...    ...   ...  
648     g   260      0     -  
649     g   200    394     -  
650     g   200      1     -  
651     g   280    750     -  
652     g     0      0     -  

[653 rows x 16 columns]

In [8]:
crx1["att2"] = pd.to_numeric(crx1["att2"])
crx1["att14"] = pd.to_numeric(crx1["att14"])

In [9]:
crx2_x = pd.get_dummies(crx1.iloc[:,0:15],drop_first=True)
crx2_y = crx1.iloc[:,15]
crx2_y = crx2_y.replace("+", 1)
crx2_y = crx2_y.replace("-", -1)
crx2_y = pd.to_numeric(crx2_y)

In [10]:
crx2_x

att2    att3  att8  att11  att14  att15  att1_b  att4_u  att4_y  \
0    30.83   0.000  1.25      1    202      0       1       1       0   
1    58.67   4.460  3.04      6     43    560       0       1       0   
2    24.50   0.500  1.50      0    280    824       0       1       0   
3    27.83   1.540  3.75      5    100      3       1       1       0   
4    20.17   5.625  1.71      0    120      0       1       1       0   
..     ...     ...   ...    ...    ...    ...     ...     ...     ...   
648  21.08  10.085  1.25      0    260      0       1       0       1   
649  22.67   0.750  2.00      2    200    394       0       1       0   
650  25.25  13.500  2.00      1    200      1       0       0       1   
651  17.92   0.205  0.04      0    280    750       1       1       0   
652  35.00   3.375  8.29      0      0      0       1       1       0   

     att5_gg  ...  att7_j  att7_n  att7_o  att7_v  att7_z  att9_t  att10_t  \
0          0  ...       0       0       0       1       0       1        1   
1          0  ...       0       0       0       0       0       1        1   
2          0  ...       0       0       0       0       0       1        0   
3          0  ...       0       0       0       1       0       1        1   
4          0  ...       0       0       0       1       0       1        0   
..       ...  ...     ...     ...     ...     ...     ...     ...      ...   
648        0  ...       0       0       0       0       0       0        0   
649        0  ...       0       0       0       1       0       0        1   
650        0  ...       0       0       0       0       0       0        1   
651        0  ...       0       0       0       1       0       0        0   
652        0  ...       0       0       0       0       0       0        0   

     att12_t  att13_p  att13_s  
0          0        0        0  
1          0        0        0  
2          0        0        0  
3          1        0        0  
4          0        0        1  
..       ...      ...      ...  
648        0        0        0  
649        1        0        0  
650        1        0        0  
651        0        0        0  
652        1        0        0  

[653 rows x 37 columns]

In [11]:
crx_x_normal = crx2_x.copy()
for i in range(crx2_x.shape[1]):
    crx_x_normal.iloc[:,i] = (crx_x_normal.iloc[:,i]-np.mean(crx_x_normal.iloc[:,i]))/np.std(crx_x_normal.iloc[:,i])
crx_x_normal

att2      att3      att8     att11     att14     att15    att1_b  \
0   -0.056962 -0.961440 -0.295171 -0.302596  0.128682 -0.193125  0.671648   
1    2.296536 -0.073565  0.236217  0.704516 -0.816802 -0.086443 -1.488875   
2   -0.592078 -0.861903 -0.220955 -0.504019  0.592504 -0.036150 -1.488875   
3   -0.310572 -0.654865  0.446990  0.503093 -0.477855 -0.192553  0.671648   
4   -0.958122  0.158358 -0.158613 -0.504019 -0.358926 -0.193125  0.671648   
..        ...       ...       ...       ...       ...       ...       ...   
648 -0.881193  1.046233 -0.295171 -0.504019  0.473575 -0.193125  0.671648   
649 -0.746780 -0.812134 -0.072523 -0.101174  0.116789 -0.118066 -1.488875   
650 -0.528676  1.726075 -0.072523 -0.302596  0.116789 -0.192934 -1.488875   
651 -1.148329 -0.920630 -0.654378 -0.504019  0.592504 -0.050247  0.671648   
652  0.295556 -0.289561  1.794756 -0.504019 -1.072499 -0.193125  0.671648   

       att4_u    att4_y   att5_gg  ...    att7_j    att7_n    att7_o  \
0    0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   
1    0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   
2    0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   
3    0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   
4    0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   
..        ...       ...       ...  ...       ...       ...       ...   
648 -1.800072  1.815503 -0.055427  ... -0.111369 -0.078507 -0.055427   
649  0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   
650 -1.800072  1.815503 -0.055427  ... -0.111369 -0.078507 -0.055427   
651  0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   
652  0.555533 -0.550811 -0.055427  ... -0.111369 -0.078507 -0.055427   

       att7_v    att7_z    att9_t   att10_t   att12_t   att13_p   att13_s  
0    0.844932 -0.111369  0.933306  1.129275 -0.927577 -0.055427 -0.297209  
1   -1.183527 -0.111369  0.933306  1.129275 -0.927577 -0.055427 -0.297209  
2   -1.183527 -0.111369  0.933306 -0.885524 -0.927577 -0.055427 -0.297209  
3    0.844932 -0.111369  0.933306  1.129275  1.078078 -0.055427 -0.297209  
4    0.844932 -0.111369  0.933306 -0.885524 -0.927577 -0.055427  3.364633  
..        ...       ...       ...       ...       ...       ...       ...  
648 -1.183527 -0.111369 -1.071460 -0.885524 -0.927577 -0.055427 -0.297209  
649  0.844932 -0.111369 -1.071460  1.129275  1.078078 -0.055427 -0.297209  
650 -1.183527 -0.111369 -1.071460  1.129275  1.078078 -0.055427 -0.297209  
651  0.844932 -0.111369 -1.071460 -0.885524 -0.927577 -0.055427 -0.297209  
652 -1.183527 -0.111369 -1.071460 -0.885524  1.078078 -0.055427 -0.297209  

[653 rows x 37 columns]

In [12]:
data_x = data.iloc[:,2:32]
data_y = data.iloc[:,1]
data_y = data_y.replace("M", 1)
data_y = data_y.replace("B", -1)
data_y = pd.to_numeric(data_y)

In [13]:
data_x_normal = data_x.copy()
for i in range(data_x.shape[1]):
    data_x_normal.iloc[:,i] = (data_x_normal.iloc[:,i]-np.mean(data_x_normal.iloc[:,i]))/np.std(data_x_normal.iloc[:,i])

In [14]:
data_x_normal

3         4         5         6         7         8         9  \
0    1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   
1    1.829821 -0.353632  1.685955  1.908708 -0.826962 -0.487072 -0.023846   
2    1.579888  0.456187  1.566503  1.558884  0.942210  1.052926  1.363478   
3   -0.768909  0.253732 -0.592687 -0.764464  3.283553  3.402909  1.915897   
4    1.750297 -1.151816  1.776573  1.826229  0.280372  0.539340  1.371011   
..        ...       ...       ...       ...       ...       ...       ...   
564  2.110995  0.721473  2.060786  2.343856  1.041842  0.219060  1.947285   
565  1.704854  2.085134  1.615931  1.723842  0.102458 -0.017833  0.693043   
566  0.702284  2.045574  0.672676  0.577953 -0.840484 -0.038680  0.046588   
567  1.838341  2.336457  1.982524  1.735218  1.525767  3.272144  3.296944   
568 -1.808401  1.221792 -1.814389 -1.347789 -3.112085 -1.150752 -1.114873   

           10        11        12  ...        23        24        25  \
0    2.532475  2.217515  2.255747  ...  1.886690 -1.359293  2.303601   
1    0.548144  0.001392 -0.868652  ...  1.805927 -0.369203  1.535126   
2    2.037231  0.939685 -0.398008  ...  1.511870 -0.023974  1.347475   
3    1.451707  2.867383  4.910919  ... -0.281464  0.133984 -0.249939   
4    1.428493 -0.009560 -0.562450  ...  1.298575 -1.466770  1.338539   
..        ...       ...       ...  ...       ...       ...       ...   
564  2.320965 -0.312589 -0.931027  ...  1.901185  0.117700  1.752563   
565  1.263669 -0.217664 -1.058611  ...  1.536720  2.047399  1.421940   
566  0.105777 -0.809117 -0.895587  ...  0.561361  1.374854  0.579001   
567  2.658866  2.137194  1.043695  ...  1.961239  2.237926  2.303601   
568 -1.261820 -0.820070 -0.561032  ... -1.410893  0.764190 -1.432735   

           26        27        28        29        30        31  Unnamed: 31  
0    2.001237  1.307686  2.616665  2.109526  2.296076  2.750622     1.937015  
1    1.890489 -0.375612 -0.430444 -0.146749  1.087084 -0.243890     0.281190  
2    1.456285  0.527407  1.082932  0.854974  1.955000  1.152255     0.201391  
3   -0.550021  3.394275  3.893397  1.989588  2.175786  6.046041     4.935010  
4    1.220724  0.220556 -0.313395  0.613179  0.729259 -0.868353    -0.397100  
..        ...       ...       ...       ...       ...       ...          ...  
564  2.015301  0.378365 -0.273318  0.664512  1.629151 -1.360158    -0.709091  
565  1.494959 -0.691230 -0.394820  0.236573  0.733827 -0.531855    -0.973978  
566  0.427906 -0.809587  0.350735  0.326767  0.414069 -1.104549    -0.318409  
567  1.653171  1.430427  3.904848  3.197605  2.289985  1.919083     2.219635  
568 -1.075813 -1.859019 -1.207552 -1.305831 -1.745063 -0.048138    -0.751207  

[569 rows x 30 columns]

In [15]:
def update_rule_LM(data,label,max_step=10,c_step=1):
    an = data.shape[1]
    n = data.shape[0]
    #所有參數估計值預設為0
    beta = np.array([0]*an,dtype="float")
    #常數c預設值也是0
    c = 0
    #suffle
    r_list = list(range(n))
    random.shuffle(r_list)
    data = data.iloc[r_list,:]
    label = label.iloc[r_list]
    #開始建立模型:
    for i in range(n):
        value = sum(data.iloc[i,:]*beta)+c
        if(value==0):
            value = -1
        #一個sample只跌代max_step次，超過還是錯的就直接跳下一個sample
        k = 0
        while ((value*label.iloc[i]<0)&(k<max_step)):
            #所有beta都要檢查更新方向
            for z in range(an):
                #計算這個bate是要增加還是減少
                if data.iloc[i,z] > 0:
                    beta[z] += label.iloc[i]
                else:
                    beta[z] -= label.iloc[i]
            c += label.iloc[i]*c_step
            k+=1
            value = sum(data.iloc[i,:]*beta)+c
            
            
    predict = []
    for i in range(n):
        value = sum(data.iloc[i,:]*beta)+c
        if(value>0):
            predict.append(1)
        else:
            predict.append(-1)
            
    predict=pd.DataFrame({"predict":predict})
    predict.index = r_list
    predict = predict.sort_index()["predict"]

    return(predict,c,beta)

In [16]:
n = data_x_normal.shape[0]
r_list = list(range(n))
random.shuffle(r_list)
data = data_x_normal.iloc[r_list,:]
label = data_y.iloc[r_list]

In [17]:
def least_squre(data,label):
    b0 = np.ones((data.shape[0], 1))
    newdata = np.hstack((data, b0))
    est_beta = np.linalg.inv(newdata.T @ newdata) @ newdata.T @ label
    predict = newdata @ est_beta
    predict_dict = {True:1,
                False:-1}
    predict = (pd.Series(predict)>0).map(predict_dict)
    return(est_beta,predict)

In [18]:
#model_n建議奇數，偶數雖然也可以，但當voted票數相等時，會直接當成0
def perception_update_LM(data,label,model_n,method,max_step=10,c_step=1):
    #指定一個seed的列表，範圍從0~1000000
    seed_list = random.sample(range(0, 1000000), model_n)
    if method == "voted":
        predict_table = pd.DataFrame(columns = list(range(model_n)), index=list(range(data.shape[0])))
        for i in range(model_n):
            random.seed(seed_list[i])
            predict,c,beta= update_rule_LM(data,label,max_step=max_step,c_step=c_step)
            predict_table.iloc[:,i] = predict
        predict = []
        for i in range(data.shape[0]):
            if(sum(predict_table.iloc[i,:])>0):
                predict.append(1)
            else:
                predict.append(-1)
        predict = pd.Series(predict)
        return(predict_table,predict)
    elif method == "average":
        est_beta = np.zeros((1, data.shape[1]+1))
        for i in range(model_n):
            random.seed(seed_list[i])
            predict,c,beta= update_rule_LM(data,label,max_step=max_step,c_step=c_step)
            est_beta[0,0] = est_beta[0,0]+c/model_n
            est_beta[0,1:] = est_beta[0,1:]+beta/model_n
        
        for i in range(data.shape[0]):
            b0 = np.ones((data.shape[0], 1))
            newdata = np.hstack((b0,data))
            predict = est_beta @ newdata.T
            predict_dict = {True:1,
                        False:-1}
            predict = (pd.Series(predict[0])>0).map(predict_dict)
        return(est_beta,predict)
            
            
        
        
    else:
        print("method must be voted or average")
        return(0)
    

In [19]:
sum(data_y)

-145

In [21]:
#data + update_rule
random.seed(6111016)
predict,c,beta= update_rule_LM(data_x_normal,data_y,max_step=10,c_step=30)
update_rule_table = confusion_matrix(data_y, predict)
print(sum(predict))
print(update_rule_table)
print("accuracy is %.4f"%((update_rule_table[0,0]+update_rule_table[1,1])/sum(sum(update_rule_table))))

-239
[[357   0]
 [ 47 165]]
accuracy is 0.9174


In [22]:
#crx + update_rule
random.seed(6111016)
predict,c,beta= update_rule_LM(crx_x_normal,crx2_y,max_step=10,c_step=30)
update_rule_table = confusion_matrix(crx2_y, predict)
print(sum(predict))
print(update_rule_table)
print("accuracy is %.4f"%((update_rule_table[0,0]+update_rule_table[1,1])/sum(sum(update_rule_table))))

-327
[[349   8]
 [141 155]]
accuracy is 0.7718


In [23]:
#data + least_squre
est_beta,predict_least_squre = least_squre(data_x_normal,data_y)
least_squre_table = confusion_matrix(data_y, predict_least_squre)
print(least_squre_table)
print("accuracy is %.4f"%((least_squre_table[0,0]+least_squre_table[1,1])/sum(sum(least_squre_table))))

[[355   2]
 [ 18 194]]
accuracy is 0.9649


In [24]:
#crx + least_squre
est_beta,predict_least_squre = least_squre(crx_x_normal,crx2_y)
least_squre_table = confusion_matrix(crx2_y, predict_least_squre)
print(least_squre_table)
print("accuracy is %.4f"%((least_squre_table[0,0]+least_squre_table[1,1])/sum(sum(least_squre_table))))

[[245 112]
 [ 94 202]]
accuracy is 0.6845


In [25]:
#data + voted perception
random.seed(6111016)
a,predict_voted = perception_update_LM(data_x_normal,data_y,model_n=25,method="voted",c_step=30)
voted_update_rule_table = confusion_matrix(data_y, predict_voted)
print(voted_update_rule_table)
print("accuracy is %.4f"%((voted_update_rule_table[0,0]+voted_update_rule_table[1,1])/sum(sum(voted_update_rule_table))))

[[351   6]
 [  7 205]]
accuracy is 0.9772


In [26]:
#crx + voted perception
random.seed(6111016)
a,predict_voted = perception_update_LM(crx_x_normal,crx2_y,model_n=25,method="voted",c_step=30)
voted_update_rule_table = confusion_matrix(crx2_y, predict_voted)
print(voted_update_rule_table)
print("accuracy is %.4f"%((voted_update_rule_table[0,0]+voted_update_rule_table[1,1])/sum(sum(voted_update_rule_table))))

[[301  56]
 [ 25 271]]
accuracy is 0.8760


In [27]:
#data + average perception
random.seed(6111016)
a,predict_voted = perception_update_LM(data_x_normal,data_y,model_n=25,method="average",c_step=30)
voted_update_rule_table = confusion_matrix(data_y, predict_voted)
print(voted_update_rule_table)
print("accuracy is %.4f"%((voted_update_rule_table[0,0]+voted_update_rule_table[1,1])/sum(sum(voted_update_rule_table))))

[[353   4]
 [  6 206]]
accuracy is 0.9824


In [28]:
#crx + average perception
random.seed(6111016)
a,predict_voted = perception_update_LM(crx_x_normal,crx2_y,model_n=25,method="average",c_step=30)
voted_update_rule_table = confusion_matrix(crx2_y, predict_voted)
print(voted_update_rule_table)
print("accuracy is %.4f"%((voted_update_rule_table[0,0]+voted_update_rule_table[1,1])/sum(sum(voted_update_rule_table))))

[[305  52]
 [ 25 271]]
accuracy is 0.8821


In [29]:
def w_estimate(beta,data,slack):
    #算距離，因為beta包含常數項，所以分母要扣掉
    dist = np.absolute(data @ beta)/(((beta@beta)-beta[len(beta)-1]**2)**(1/2))
    judge = (dist > slack).astype(int)
    return(dist @ judge)
def update_rule_LM_rewrite(data,label,max_iter=5,c_step=1,slack=0):
    an = data.shape[1]
    n = data.shape[0]
    #所有參數估計值預設為6
    beta = np.array([6]*(an+1),dtype="float")
    #常數c預設值設為-an
    beta[-1] = -an
    
    #suffle
    r_list = list(range(n))
    random.shuffle(r_list)
    data = data.iloc[r_list,:]
    label = label.iloc[r_list]
    b0 = np.ones((data.shape[0], 1))
    newdata = np.hstack((data, b0))
    #計算起始線的W
    dist = w_estimate(beta,newdata,slack)
    #開始建立模型:
    iterate = 0
    keep = True
    accept = 0
    drop = 0
    while (iterate < max_iter)&keep:
        keep = False
        iterate +=1
        for i in range(n):
            value = sum(newdata[i,:]*beta)
            if(value==0):
                value = -1

            if(value*label.iloc[i]<0):
                #所有beta都要檢查更新方向
                
                for z in range(an):
                    #計算這個bate是要增加還是減少
                    newbeta = beta.copy()
                    if newdata[i,z] > 0:
                        newbeta[z] += label.iloc[i]
                        
                    else:
                        newbeta[z] -= label.iloc[i]

                    newdist = w_estimate(newbeta,newdata,slack)
                #看是否要進行疊代，每個參數更改後都進行一次
                if newdist < dist:
                    dist = newdist
                    beta = newbeta
                #看常數是否要進行疊代
                newbeta = beta.copy()
                newbeta[-1] += label.iloc[i]*c_step
                
                newdist = w_estimate(newbeta,newdata,slack)
                if newdist < dist:
                    dist = newdist
                    beta = newbeta
                    keep = True
                    accept+=1
                else:
                    drop+=1
                    
    print("stop at iterate:",iterate)
    predict = []
    for i in range(n):
        value = sum(newdata[i,:]*beta)
        if(value>0):
            predict.append(1)
        else:
            predict.append(-1)
            
    predict=pd.DataFrame({"predict":predict})
    predict.index = r_list
    predict = predict.sort_index()["predict"]

    return(predict,c,beta,drop,accept)

In [30]:
#data+ minimizing the ||w||^2
random.seed(6111016)
predict_rewrite,c,beta,drop,accept = update_rule_LM_rewrite(data_x_normal,data_y,max_iter=20,c_step=2,slack=0)
rewrite_table = confusion_matrix(data_y, predict_rewrite)
print(sum(predict_rewrite))
print(rewrite_table)
print("accuracy is %.4f"%((rewrite_table[0,0]+rewrite_table[1,1])/sum(sum(rewrite_table))))
print(drop,accept)

stop at iterate: 8
-5
[[256 101]
 [ 31 181]]
accuracy is 0.7680
869 42


In [31]:
#data+ minimizing the ||w||^2+weighting value C != 0
random.seed(6111016)
predict_rewrite,c,beta,drop,accept = update_rule_LM_rewrite(data_x_normal,data_y,max_iter=20,c_step=2,slack=3)
rewrite_table = confusion_matrix(data_y, predict_rewrite)
print(sum(predict_rewrite))
print(rewrite_table)
print("accuracy is %.4f"%((rewrite_table[0,0]+rewrite_table[1,1])/sum(sum(rewrite_table))))
print(drop,accept)

stop at iterate: 2
-129
[[324  33]
 [ 25 187]]
accuracy is 0.8981
104 14


In [32]:
#data+ minimizing the ||w||^2
random.seed(6111016)
predict_rewrite,c,beta,drop,accept = update_rule_LM_rewrite(crx_x_normal,crx2_y,max_iter=20,c_step=2,slack=0)
rewrite_table = confusion_matrix(crx2_y, predict_rewrite)
print(sum(predict_rewrite))
print(rewrite_table)
print("accuracy is %.4f"%((rewrite_table[0,0]+rewrite_table[1,1])/sum(sum(rewrite_table))))
print(drop,accept)

stop at iterate: 2
-5
[[246 111]
 [ 83 213]]
accuracy is 0.7029
359 21


In [33]:
#data+ minimizing the ||w||^2+weighting value C != 0
random.seed(6111016)
predict_rewrite,c,beta,drop,accept = update_rule_LM_rewrite(crx_x_normal,crx2_y,max_iter=20,c_step=2,slack=0.5)
rewrite_table = confusion_matrix(crx2_y, predict_rewrite)
print(sum(predict_rewrite))
print(rewrite_table)
print("accuracy is %.4f"%((rewrite_table[0,0]+rewrite_table[1,1])/sum(sum(rewrite_table))))
print(drop,accept)

stop at iterate: 2
-29
[[250 107]
 [ 91 205]]
accuracy is 0.6968
371 20


In [34]:
from sklearn.svm import SVC

In [35]:
svm_data = SVC(kernel="linear")
svm_data.fit(data_x_normal,data_y)
svm_data_predict = svm_data.predict(data_x_normal)
rewrite_table = confusion_matrix(data_y, svm_data_predict)
print(sum(predict_rewrite))
print(rewrite_table)
print("accuracy is %.4f"%((rewrite_table[0,0]+rewrite_table[1,1])/sum(sum(rewrite_table))))

-29
[[355   2]
 [  5 207]]
accuracy is 0.9877


In [36]:
svm_data = SVC(kernel="linear")
svm_data.fit(crx_x_normal,crx2_y)
svm_data_predict = svm_data.predict(crx_x_normal)
rewrite_table = confusion_matrix(crx2_y, svm_data_predict)
print(sum(predict_rewrite))
print(rewrite_table)
print("accuracy is %.4f"%((rewrite_table[0,0]+rewrite_table[1,1])/sum(sum(rewrite_table))))

-29
[[286  71]
 [ 16 280]]
accuracy is 0.8668
